project:
  type: website

website:
  title: "University of Queensland Biology Postgraduate club"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Campbell98
      - icon: facebook
        href: https://www.facebook.com/groups/biolpgc/
format:
  html:
    theme: Pulse
    css: styles.css

editor: visual

